# LoRaWAN network server to apply device configurations
[chirpstack]

# This must point to the API interface.
endpoint = "localhost:8080"

# The tenants targeted by the algorithm (empty = all)
tenant_names = ["ChirpStack"]

# Time-series database for the metrics collection system
[influxdb]

# The endpoint of your InfluxDB instance
endpoint = "localhost:8086"

# InfluxDB authentication token
token = "token"

# InfluxDB organization
org = "cnam"

# InfluxDB bucket where data is stored
bucket = "chirpstack"
